# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\dashboardContent\dashboardContent.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 300)
        Form.setMinimumSize(QtCore.QSize(300, 300))
        Form.setMaximumSize(QtCore.QSize(300, 300))
        Form.setStyleSheet("QWidget {\n"
"    background-color: rgb(48, 108, 149);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QWidget QLabel {\n"
"    color: #fff;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.content_1_title = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.content_1_title.setFont(font)
        self.content_1_title.setAlignment(QtCore.Qt.AlignCenter)
        self.content_1_title.setObjectName("content_1_title")
        self.verticalLayout.addWidget(self.content_1_title)
        self.temperature_1_widget = QtWidgets.QWidget(Form)
        self.temperature_1_widget.setObjectName("temperature_1_widget")
        self.temperature_1_widget_layout = QtWidgets.QHBoxLayout(self.temperature_1_widget)
        self.temperature_1_widget_layout.setContentsMargins(0, 0, 0, 0)
        self.temperature_1_widget_layout.setSpacing(0)
        self.temperature_1_widget_layout.setObjectName("temperature_1_widget_layout")
        self.temperature_1_icon = QtWidgets.QPushButton(self.temperature_1_widget)
        self.temperature_1_icon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\ui\\dashboardContent\\../../resources/icons/thermometer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.temperature_1_icon.setIcon(icon)
        self.temperature_1_icon.setIconSize(QtCore.QSize(56, 56))
        self.temperature_1_icon.setObjectName("temperature_1_icon")
        self.temperature_1_widget_layout.addWidget(self.temperature_1_icon)
        self.temperature_1 = QtWidgets.QLabel(self.temperature_1_widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.temperature_1.setFont(font)
        self.temperature_1.setScaledContents(True)
        self.temperature_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.temperature_1.setObjectName("temperature_1")
        self.temperature_1_widget_layout.addWidget(self.temperature_1)
        self.temperature_1_value = QtWidgets.QLabel(self.temperature_1_widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.temperature_1_value.setFont(font)
        self.temperature_1_value.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"margin: 20px 0px;\n"
"color: rgb(255, 0, 0)")
        self.temperature_1_value.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.temperature_1_value.setObjectName("temperature_1_value")
        self.temperature_1_widget_layout.addWidget(self.temperature_1_value)
        self.temperature_1_widget_layout.setStretch(1, 1)
        self.temperature_1_widget_layout.setStretch(2, 1)
        self.verticalLayout.addWidget(self.temperature_1_widget)
        self.light_1_widget = QtWidgets.QWidget(Form)
        self.light_1_widget.setObjectName("light_1_widget")
        self.light_1_widget_layout = QtWidgets.QHBoxLayout(self.light_1_widget)
        self.light_1_widget_layout.setContentsMargins(0, 0, 0, 0)
        self.light_1_widget_layout.setSpacing(0)
        self.light_1_widget_layout.setObjectName("light_1_widget_layout")
        self.light_1_icon = QtWidgets.QPushButton(self.light_1_widget)
        self.light_1_icon.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\ui\\dashboardContent\\../../resources/icons/lamp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.light_1_icon.setIcon(icon1)
        self.light_1_icon.setIconSize(QtCore.QSize(56, 56))
        self.light_1_icon.setObjectName("light_1_icon")
        self.light_1_widget_layout.addWidget(self.light_1_icon, 0, QtCore.Qt.AlignLeft)
        self.light_1 = QtWidgets.QLabel(self.light_1_widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.light_1.setFont(font)
        self.light_1.setObjectName("light_1")
        self.light_1_widget_layout.addWidget(self.light_1, 0, QtCore.Qt.AlignLeft)
        self.light_1_switch = QtWidgets.QPushButton(self.light_1_widget)
        self.light_1_switch.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\ui\\dashboardContent\\../../resources/icons/switch-on.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.light_1_switch.setIcon(icon2)
        self.light_1_switch.setIconSize(QtCore.QSize(64, 64))
        self.light_1_switch.setObjectName("light_1_switch")
        self.light_1_widget_layout.addWidget(self.light_1_switch)
        self.light_1_widget_layout.setStretch(1, 1)
        self.verticalLayout.addWidget(self.light_1_widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.content_1_title.setText(_translate("Form", "Cuisine"))
        self.temperature_1.setText(_translate("Form", "Temperature :"))
        self.temperature_1_value.setText(_translate("Form", "29* C"))
        self.light_1.setText(_translate("Form", "Lumière"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
