# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\login\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginWindow(object):
    def setupUi(self, loginWindow):
        loginWindow.setObjectName("loginWindow")
        loginWindow.resize(650, 500)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(loginWindow.sizePolicy().hasHeightForWidth())
        loginWindow.setSizePolicy(sizePolicy)
        loginWindow.setMinimumSize(QtCore.QSize(650, 500))
        loginWindow.setMaximumSize(QtCore.QSize(650, 531))
        font = QtGui.QFont()
        font.setPointSize(11)
        loginWindow.setFont(font)
        loginWindow.setStyleSheet(
            "#leftWidget {\n"
            "    background-color: #0e273c\n"
            "}\n"
            "\n"
            "#formWidget {\n"
            "    background-color: rgb(252, 252, 252)\n"
            "}\n"
            "\n"
            "QLineEdit {\n"
            "background: #00000000;\n"
            "border: 2px solid rgba(0, 0, 0, 0);\n"
            "border-bottom-color: rgba(0, 0, 0, 200);\n"
            "color: #000;\n"
            "padding: 10px;\n"
            "}\n"
            "\n"
            "QLineEdit:hover {\n"
            "    border-bottom-color: #fa8334;\n"
            "}\n"
            "\n"
            "QLineEdit:focus {\n"
            "    border-bottom-color: rgb(255, 159, 3);\n"
            "    outline: none;\n"
            "}\n"
            "\n"
            "QPushButton {\n"
            "  color: rbg(0, 0, 0, 200)\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(255, 159, 3);\n"
            "    color: #fff;\n"
            "    outline: none;\n"
            "    border: none\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: #fa8334;\n"
            "    color: rgb(231, 231, 231);\n"
            "    border: 2px solid rgba(0, 0, 0, 0);\n"
            "}\n"
            "\n"
            "QPushButton#quitBtn {\n"
            "   border: none;\n"
            "   background-color: rbga(0, 0, 0, 0);\n"
            "   height: 50px;\n"
            "   width: 40px;\n"
            "   border-radius: 20px\n"
            "}\n"
            "\n"
            "QPushButton#quitBtn:hover {\n"
            "   background-color: rgb(255, 159, 3)\n"
            "}\n"
        )
        self.gridLayout = QtWidgets.QGridLayout(loginWindow)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.leftWidget = QtWidgets.QWidget(loginWindow)
        self.leftWidget.setStyleSheet("color: #fff")
        self.leftWidget.setObjectName("leftWidget")
        self.leftLayout = QtWidgets.QVBoxLayout(self.leftWidget)
        self.leftLayout.setContentsMargins(10, 40, 10, 0)
        self.leftLayout.setSpacing(20)
        self.leftLayout.setObjectName("leftLayout")
        self.titleLabel = QtWidgets.QLabel(self.leftWidget)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(40)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("")
        self.titleLabel.setScaledContents(True)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setWordWrap(True)
        self.titleLabel.setObjectName("titleLabel")
        self.leftLayout.addWidget(self.titleLabel)
        self.descLabel = QtWidgets.QLabel(self.leftWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.descLabel.setFont(font)
        self.descLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.descLabel.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.descLabel.setWordWrap(True)
        self.descLabel.setIndent(-1)
        self.descLabel.setObjectName("descLabel")
        self.leftLayout.addWidget(self.descLabel, 0, QtCore.Qt.AlignHCenter)
        self.label = QtWidgets.QLabel(self.leftWidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.leftLayout.addWidget(self.label)
        self.leftLayout.setStretch(2, 1)
        self.gridLayout.addWidget(self.leftWidget, 0, 0, 1, 1)
        self.formWidget = QtWidgets.QWidget(loginWindow)
        self.formWidget.setStyleSheet("")
        self.formWidget.setObjectName("formWidget")
        self.formLayout = QtWidgets.QVBoxLayout(self.formWidget)
        self.formLayout.setContentsMargins(25, 70, 25, 20)
        self.formLayout.setSpacing(57)
        self.formLayout.setObjectName("formLayout")
        self.loginLabel = QtWidgets.QLabel(self.formWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.loginLabel.setFont(font)
        self.loginLabel.setStyleSheet("color: rbg(0, 0, 0, 200)")
        self.loginLabel.setObjectName("loginLabel")
        self.formLayout.addWidget(
            self.loginLabel, 0, QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop
        )
        self.usernameEntry = QtWidgets.QLineEdit(self.formWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.usernameEntry.setFont(font)
        self.usernameEntry.setStyleSheet("")
        self.usernameEntry.setObjectName("usernameEntry")
        self.formLayout.addWidget(self.usernameEntry, 0, QtCore.Qt.AlignTop)
        self.passwordEntry = QtWidgets.QLineEdit(self.formWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.passwordEntry.setFont(font)
        self.passwordEntry.setStyleSheet("")
        self.passwordEntry.setObjectName("passwordEntry")
        self.formLayout.addWidget(self.passwordEntry)
        self.loginBtn = QtWidgets.QPushButton(self.formWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginBtn.sizePolicy().hasHeightForWidth())
        self.loginBtn.setSizePolicy(sizePolicy)
        self.loginBtn.setMinimumSize(QtCore.QSize(0, 60))
        self.loginBtn.setMaximumSize(QtCore.QSize(16777215, 60))
        self.loginBtn.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.loginBtn.setFont(font)
        self.loginBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginBtn.setStyleSheet("")
        self.loginBtn.setObjectName("loginBtn")
        self.formLayout.addWidget(self.loginBtn)
        self.quitBtn = QtWidgets.QPushButton(self.formWidget)
        self.quitBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.quitBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(".\\ui\\login\\../../resources/icons/power-button.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.quitBtn.setIcon(icon)
        self.quitBtn.setIconSize(QtCore.QSize(36, 36))
        self.quitBtn.setObjectName("quitBtn")
        self.formLayout.addWidget(
            self.quitBtn, 0, QtCore.Qt.AlignRight | QtCore.Qt.AlignBottom
        )
        self.formLayout.setStretch(1, 1)
        self.formLayout.setStretch(2, 1)
        self.formLayout.setStretch(3, 1)
        self.formLayout.setStretch(4, 1)
        self.gridLayout.addWidget(self.formWidget, 0, 1, 1, 1)

        self.retranslateUi(loginWindow)
        QtCore.QMetaObject.connectSlotsByName(loginWindow)

        self.quitBtn.clicked.connect(QtCore.QCoreApplication.instance().quit)
        self.loginBtn.clicked.connect(lambda: print("connect"))

    def retranslateUi(self, loginWindow):
        _translate = QtCore.QCoreApplication.translate
        loginWindow.setWindowTitle(_translate("loginWindow", "Se connecter"))
        self.titleLabel.setText(_translate("loginWindow", "nyTranoko"))
        self.descLabel.setText(
            _translate(
                "loginWindow",
                '"Faites confiance à nytranoko pour la sécurité de votre maison."',
            )
        )
        self.loginLabel.setText(_translate("loginWindow", "Se connecter"))
        self.usernameEntry.setPlaceholderText(
            _translate("loginWindow", "Nom d'utilisateur")
        )
        self.passwordEntry.setPlaceholderText(_translate("loginWindow", "Mot de passe"))
        self.loginBtn.setText(_translate("loginWindow", "Connexion"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    loginWindow = QtWidgets.QWidget()
    ui = Ui_loginWindow()
    ui.setupUi(loginWindow)
    loginWindow.show()
    sys.exit(app.exec_())
