# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\popWindow\pop-up.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_closeAppWidget(object):
    def setupUi(self, closeAppWidget):
        closeAppWidget.setObjectName("closeAppWidget")
        closeAppWidget.resize(360, 140)
        closeAppWidget.setStyleSheet("#closeAppWidget {\n"
"    border-radius: 20px;\n"
"    background-color: #0e273c;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #fff\n"
"}\n"
"QPushButton {\n"
"    padding: 10px 0;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(252,252,252);\n"
"    color: #0e273c\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(255, 159, 3);\n"
"    color: #fff;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.closeAppWidgetLayout = QtWidgets.QVBoxLayout(closeAppWidget)
        self.closeAppWidgetLayout.setObjectName("closeAppWidgetLayout")
        self.text = QtWidgets.QLabel(closeAppWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.text.setFont(font)
        self.text.setStyleSheet("")
        self.text.setAlignment(QtCore.Qt.AlignCenter)
        self.text.setObjectName("text")
        self.closeAppWidgetLayout.addWidget(self.text)
        self.buttonWidget = QtWidgets.QWidget(closeAppWidget)
        self.buttonWidget.setObjectName("buttonWidget")
        self.buttonWidgetLayout = QtWidgets.QHBoxLayout(self.buttonWidget)
        self.buttonWidgetLayout.setObjectName("buttonWidgetLayout")
        self.yesButton = QtWidgets.QPushButton(self.buttonWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.yesButton.setFont(font)
        self.yesButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.yesButton.setObjectName("yesButton")
        self.buttonWidgetLayout.addWidget(self.yesButton)
        self.cancelButton = QtWidgets.QPushButton(self.buttonWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cancelButton.setFont(font)
        self.cancelButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancelButton.setObjectName("cancelButton")
        self.buttonWidgetLayout.addWidget(self.cancelButton)
        self.closeAppWidgetLayout.addWidget(self.buttonWidget)

        self.retranslateUi(closeAppWidget)
        QtCore.QMetaObject.connectSlotsByName(closeAppWidget)

    def retranslateUi(self, closeAppWidget):
        _translate = QtCore.QCoreApplication.translate
        closeAppWidget.setWindowTitle(_translate("closeAppWidget", "Form"))
        self.text.setText(_translate("closeAppWidget", "Voulez-vous fermer l\'application?"))
        self.yesButton.setText(_translate("closeAppWidget", "Oui"))
        self.cancelButton.setText(_translate("closeAppWidget", "Annuler"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    closeAppWidget = QtWidgets.QWidget()
    ui = Ui_closeAppWidget()
    ui.setupUi(closeAppWidget)
    closeAppWidget.show()
    sys.exit(app.exec_())
