# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\home\home.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ..dashboardContent.dashboardContent_ui import Ui_DashboardContent


class Ui_homeWindow(object):
    def setupUi(self, homeWindow):
        homeWindow.setObjectName("homeWindow")
        homeWindow.resize(1077, 604)
        homeWindow.setStyleSheet("background-color: rgb(250, 250, 250)")
        self.homeWindowLayout = QtWidgets.QHBoxLayout(homeWindow)
        self.homeWindowLayout.setContentsMargins(15, 15, 0, 15)
        self.homeWindowLayout.setSpacing(10)
        self.homeWindowLayout.setObjectName("homeWindowLayout")
        self.sidebar = QtWidgets.QWidget(homeWindow)
        self.sidebar.setStyleSheet(
            "QWidget {\n"
            "    background-color: #0e273c;\n"
            "    color: #fff;\n"
            "    border-radius: 20px;\n"
            "}\n"
            "\n"
            "QPushButton {\n"
            "    padding: 5px;\n"
            "}\n"
            "\n"
            ""
        )
        self.sidebar.setObjectName("sidebar")
        self.sidebarLayout = QtWidgets.QVBoxLayout(self.sidebar)
        self.sidebarLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.sidebarLayout.setContentsMargins(15, -1, 15, -1)
        self.sidebarLayout.setSpacing(15)
        self.sidebarLayout.setObjectName("sidebarLayout")
        self.label = QtWidgets.QLabel(self.sidebar)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet(
            "QLabel {\n"
            "    padding:10px;\n"
            "    border: 4px solid rgba(0, 0, 0, 0);\n"
            "    border-bottom-color: #fff;\n"
            "    border-radius: 0px;\n"
            "    text-align: center\n"
            "}"
        )
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.sidebarLayout.addWidget(
            self.label, 0, QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop
        )
        self.settingsWidget = QtWidgets.QWidget(self.sidebar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.settingsWidget.sizePolicy().hasHeightForWidth()
        )
        self.settingsWidget.setSizePolicy(sizePolicy)
        self.settingsWidget.setAutoFillBackground(False)
        self.settingsWidget.setStyleSheet(
            "QWidget{    \n"
            "    background-color: rgba(0, 0, 0, 0);\n"
            "    border-radius: 20px;\n"
            "}\n"
            "\n"
            "QPushButton {\n"
            "    border: 2px solid rgba(0, 0, 0, 0);\n"
            "    background-color: rbga(0, 0, 0, 0);\n"
            "    border-radius: none;\n"
            "    outline: none;\n"
            "    text-align: left\n"
            "}\n"
            "QPushButton:hover {\n"
            "    border: 2px solid rgba(0, 0, 0, 0);\n"
            "    outline: none;\n"
            "    border-bottom-color: rgb(255, 159, 3);\n"
            "    color:  rgb(255, 159, 3);\n"
            "\n"
            "}"
        )
        self.settingsWidget.setObjectName("settingsWidget")
        self.settingsWidgetLayout = QtWidgets.QVBoxLayout(self.settingsWidget)
        self.settingsWidgetLayout.setContentsMargins(5, 10, 5, 10)
        self.settingsWidgetLayout.setSpacing(6)
        self.settingsWidgetLayout.setObjectName("settingsWidgetLayout")
        self.dashBtn = QtWidgets.QPushButton(self.settingsWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dashBtn.sizePolicy().hasHeightForWidth())
        self.dashBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.dashBtn.setFont(font)
        self.dashBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dashBtn.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(".\\ui\\home\\../../resources/icons/dashboard.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.dashBtn.setIcon(icon)
        self.dashBtn.setIconSize(QtCore.QSize(32, 32))
        self.dashBtn.setObjectName("dashBtn")
        self.settingsWidgetLayout.addWidget(self.dashBtn)
        self.controlBtn = QtWidgets.QPushButton(self.settingsWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.controlBtn.setFont(font)
        self.controlBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(".\\ui\\home\\../../resources/icons/energy-system.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.controlBtn.setIcon(icon1)
        self.controlBtn.setIconSize(QtCore.QSize(32, 32))
        self.controlBtn.setObjectName("controlBtn")
        self.settingsWidgetLayout.addWidget(self.controlBtn)
        self.profileBtn = QtWidgets.QPushButton(self.settingsWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.profileBtn.setFont(font)
        self.profileBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap(".\\ui\\home\\../../resources/icons/profile.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.profileBtn.setIcon(icon2)
        self.profileBtn.setIconSize(QtCore.QSize(32, 32))
        self.profileBtn.setObjectName("profileBtn")
        self.settingsWidgetLayout.addWidget(self.profileBtn)
        self.emptyLabel = QtWidgets.QLabel(self.settingsWidget)
        self.emptyLabel.setText("")
        self.emptyLabel.setObjectName("emptyLabel")
        self.settingsWidgetLayout.addWidget(self.emptyLabel)
        self.sidebarLayout.addWidget(self.settingsWidget)
        self.quitWidget = QtWidgets.QWidget(self.sidebar)
        self.quitWidget.setStyleSheet(
            "QWidget {\n"
            "    background-color: rgba(0, 0, 0, 0);\n"
            "    border-radius: 20px;\n"
            "    color: #fff;\n"
            "}\n"
            "\n"
            "QPushButton {\n"
            "    border: 2px solid rgba(0, 0, 0, 0);\n"
            "    background-color: rbga(0, 0, 0, 0);\n"
            "    border-radius: none;\n"
            "    outline: none;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    \n"
            "    color: rgb(255, 159, 3);\n"
            "}"
        )
        self.quitWidget.setObjectName("quitWidget")
        self.quitWidgetLayout = QtWidgets.QVBoxLayout(self.quitWidget)
        self.quitWidgetLayout.setContentsMargins(0, 10, 0, 10)
        self.quitWidgetLayout.setSpacing(10)
        self.quitWidgetLayout.setObjectName("quitWidgetLayout")
        self.logoutBtn = QtWidgets.QPushButton(self.quitWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.logoutBtn.setFont(font)
        self.logoutBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(
            QtGui.QPixmap(".\\ui\\home\\../../resources/icons/check-out.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.logoutBtn.setIcon(icon3)
        self.logoutBtn.setIconSize(QtCore.QSize(32, 32))
        self.logoutBtn.setObjectName("logoutBtn")
        self.quitWidgetLayout.addWidget(self.logoutBtn, 0, QtCore.Qt.AlignLeft)
        self.quitBtn = QtWidgets.QPushButton(self.quitWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.quitBtn.setFont(font)
        self.quitBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(
            QtGui.QPixmap(".\\ui\\home\\../../resources/icons/switch.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.quitBtn.setIcon(icon4)
        self.quitBtn.setIconSize(QtCore.QSize(30, 30))
        self.quitBtn.setObjectName("quitBtn")
        self.quitWidgetLayout.addWidget(self.quitBtn, 0, QtCore.Qt.AlignLeft)
        self.sidebarLayout.addWidget(self.quitWidget, 0, QtCore.Qt.AlignBottom)
        self.sidebarLayout.setStretch(1, 1)
        self.homeWindowLayout.addWidget(self.sidebar)
        self.mainWidget = QtWidgets.QStackedWidget(homeWindow)
        self.mainWidget.setStyleSheet(
            "QStackedWidget > QWidget > QLabel {\n"
            "    padding-top: 40px;\n"
            "    background-color: rgba(0, 0, 0, 0);\n"
            "    color: #0e273c;\n"
            "}\n"
            ""
        )
        self.mainWidget.setObjectName("mainWidget")
        self.dashboard = QtWidgets.QWidget()
        self.dashboard.setStyleSheet("")
        self.dashboard.setObjectName("dashboard")
        self.dashboardLayout = QtWidgets.QVBoxLayout(self.dashboard)
        self.dashboardLayout.setContentsMargins(0, 0, -1, 0)
        self.dashboardLayout.setSpacing(0)
        self.dashboardLayout.setObjectName("dashboardLayout")
        self.dashboardTitle = QtWidgets.QLabel(self.dashboard)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.dashboardTitle.setFont(font)
        self.dashboardTitle.setStyleSheet("")
        self.dashboardTitle.setObjectName("dashboardTitle")
        self.dashboardLayout.addWidget(self.dashboardTitle)
        self.scrollArea = QtWidgets.QScrollArea(self.dashboard)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaContainer = QtWidgets.QWidget()
        self.scrollAreaContainer.setGeometry(QtCore.QRect(0, 0, 787, 501))
        self.scrollAreaContainer.setObjectName("scrollAreaContainer")
        self.scrollAreaContainerLayout = QtWidgets.QGridLayout(self.scrollAreaContainer)
        self.scrollAreaContainerLayout.setObjectName("scrollAreaContainerLayout")
        self.dashboardContainer = QtWidgets.QWidget(self.scrollAreaContainer)
        self.dashboardContainer.setStyleSheet("")
        self.dashboardContainer.setObjectName("dashboardContainer")
        self.dashboardContainerLayout = QtWidgets.QGridLayout(self.dashboardContainer)
        self.dashboardContainerLayout.setContentsMargins(0, 0, 0, 0)
        self.dashboardContainerLayout.setSpacing(10)
        self.dashboardContainerLayout.setObjectName("dashboardContainerLayout")
        self.content_1 = QtWidgets.QWidget(self.dashboardContainer)
        self.content_1.setMinimumSize(QtCore.QSize(300, 300))
        self.content_1.setMaximumSize(QtCore.QSize(300, 300))
        self.content_1.setStyleSheet(
            "QWidget {\n"
            "    background-color: rgb(48, 108, 149);\n"
            "    border-radius: 20px;\n"
            "}\n"
            "\n"
            "QWidget QLabel {\n"
            "    color: #fff;\n"
            "}"
        )
        self.content_1.setObjectName("content_1")
        self.content_1_layout = QtWidgets.QVBoxLayout(self.content_1)
        self.content_1_layout.setSpacing(0)
        self.content_1_layout.setObjectName("content_1_layout")
        self.content_1_title = QtWidgets.QLabel(self.content_1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.content_1_title.setFont(font)
        self.content_1_title.setAlignment(QtCore.Qt.AlignCenter)
        self.content_1_title.setObjectName("content_1_title")
        self.content_1_layout.addWidget(self.content_1_title)

        self.temperature_1_widget = QtWidgets.QWidget(self.content_1)
        self.temperature_1_widget.setObjectName("temperature_1_widget")
        self.temperature_1_widget_layout = QtWidgets.QHBoxLayout(
            self.temperature_1_widget
        )
        self.temperature_1_widget_layout.setContentsMargins(0, 0, 0, 0)
        self.temperature_1_widget_layout.setSpacing(0)
        self.temperature_1_widget_layout.setObjectName("temperature_1_widget_layout")
        self.temperature_1_icon = QtWidgets.QPushButton(self.temperature_1_widget)
        self.temperature_1_icon.setText("")

        icon5 = QtGui.QIcon()
        icon5.addPixmap(
            QtGui.QPixmap(".\\ui\\home\\../../resources/icons/thermometer.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.temperature_1_icon.setIcon(icon5)
        self.temperature_1_icon.setIconSize(QtCore.QSize(56, 56))
        self.temperature_1_icon.setObjectName("temperature_1_icon")
        self.temperature_1_widget_layout.addWidget(self.temperature_1_icon)

        self.temperature_1 = QtWidgets.QLabel(self.temperature_1_widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.temperature_1.setFont(font)
        self.temperature_1.setScaledContents(True)
        self.temperature_1.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.temperature_1.setObjectName("temperature_1")
        self.temperature_1_widget_layout.addWidget(self.temperature_1)
        self.temperature_1_value = QtWidgets.QLabel(self.temperature_1_widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.temperature_1_value.setFont(font)
        self.temperature_1_value.setStyleSheet(
            "background-color: rgb(250, 250, 250);\n"
            "margin: 20px 0px;\n"
            "color: rgb(255, 0, 0)"
        )
        self.temperature_1_value.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.temperature_1_value.setObjectName("temperature_1_value")
        self.temperature_1_widget_layout.addWidget(self.temperature_1_value)
        self.temperature_1_widget_layout.setStretch(1, 1)
        self.temperature_1_widget_layout.setStretch(2, 1)
        self.content_1_layout.addWidget(self.temperature_1_widget)

        self.light_1_widget = QtWidgets.QWidget(self.content_1)
        self.light_1_widget.setObjectName("light_1_widget")
        self.light_1_widget_layout = QtWidgets.QHBoxLayout(self.light_1_widget)
        self.light_1_widget_layout.setContentsMargins(0, 0, 0, 0)
        self.light_1_widget_layout.setSpacing(0)
        self.light_1_widget_layout.setObjectName("light_1_widget_layout")
        self.light_1_icon = QtWidgets.QPushButton(self.light_1_widget)
        self.light_1_icon.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(
            QtGui.QPixmap(".\\ui\\home\\../../resources/icons/lamp.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.light_1_icon.setIcon(icon6)
        self.light_1_icon.setIconSize(QtCore.QSize(56, 56))
        self.light_1_icon.setObjectName("light_1_icon")
        self.light_1_widget_layout.addWidget(self.light_1_icon, 0, QtCore.Qt.AlignLeft)
        self.light_1 = QtWidgets.QLabel(self.light_1_widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.light_1.setFont(font)
        self.light_1.setObjectName("light_1")
        self.light_1_widget_layout.addWidget(self.light_1, 0, QtCore.Qt.AlignLeft)
        self.light_1_switch = QtWidgets.QPushButton(self.light_1_widget)
        self.light_1_switch.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(
            QtGui.QPixmap(".\\ui\\home\\../../resources/icons/switch-on.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.light_1_switch.setIcon(icon7)
        self.light_1_switch.setIconSize(QtCore.QSize(64, 64))
        self.light_1_switch.setObjectName("light_1_switch")
        self.light_1_widget_layout.addWidget(self.light_1_switch)
        self.light_1_widget_layout.setStretch(1, 1)
        self.content_1_layout.addWidget(self.light_1_widget)
        self.dashboardContainerLayout.addWidget(
            self.content_1, 0, 0, 1, 1, QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop
        )
        self.dashboardContainerLayout.addWidget(
            Ui_DashboardContent("Cuisine"), 0, 1, 1, 1
        )
        self.dashboardContainerLayout.addWidget(
            Ui_DashboardContent("Chambre à coucher"), 0, 2, 1, 1
        )

        self.scrollAreaContainerLayout.addWidget(self.dashboardContainer, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaContainer)
        self.dashboardLayout.addWidget(self.scrollArea)
        self.mainWidget.addWidget(self.dashboard)
        self.control = QtWidgets.QWidget()
        self.control.setObjectName("control")
        self.controlLayout = QtWidgets.QVBoxLayout(self.control)
        self.controlLayout.setContentsMargins(0, 0, -1, 0)
        self.controlLayout.setSpacing(0)
        self.controlLayout.setObjectName("controlLayout")
        self.controlTitle = QtWidgets.QLabel(self.control)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.controlTitle.setFont(font)
        self.controlTitle.setStyleSheet("")
        self.controlTitle.setObjectName("controlTitle")
        self.controlLayout.addWidget(self.controlTitle, 0, QtCore.Qt.AlignTop)
        self.widget = QtWidgets.QWidget(self.control)
        self.widget.setObjectName("widget")
        self.controlLayout.addWidget(self.widget)
        self.controlLayout.setStretch(1, 1)
        self.mainWidget.addWidget(self.control)
        self.profile = QtWidgets.QWidget()
        self.profile.setStyleSheet("")
        self.profile.setObjectName("profile")
        self.profileLayout = QtWidgets.QVBoxLayout(self.profile)
        self.profileLayout.setContentsMargins(0, 0, 0, 0)
        self.profileLayout.setSpacing(0)
        self.profileLayout.setObjectName("profileLayout")
        self.profileTitle = QtWidgets.QLabel(self.profile)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.profileTitle.setFont(font)
        self.profileTitle.setStyleSheet("")
        self.profileTitle.setObjectName("profileTitle")
        self.profileLayout.addWidget(self.profileTitle, 0, QtCore.Qt.AlignTop)
        self.widget_3 = QtWidgets.QWidget(self.profile)
        self.widget_3.setObjectName("widget_3")
        self.profileLayout.addWidget(self.widget_3)
        self.profileLayout.setStretch(1, 1)
        self.mainWidget.addWidget(self.profile)
        self.homeWindowLayout.addWidget(self.mainWidget)

        self.retranslateUi(homeWindow)
        self.mainWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(homeWindow)

    def retranslateUi(self, homeWindow):
        _translate = QtCore.QCoreApplication.translate
        homeWindow.setWindowTitle(_translate("homeWindow", "Home"))
        self.label.setText(_translate("homeWindow", "nyTranoko"))
        self.dashBtn.setText(_translate("homeWindow", "Dashboard"))
        self.controlBtn.setText(_translate("homeWindow", "Control"))
        self.profileBtn.setText(_translate("homeWindow", "Profile"))
        self.logoutBtn.setText(_translate("homeWindow", "Déconnexion"))
        self.quitBtn.setText(_translate("homeWindow", "Quitter"))
        self.dashboardTitle.setText(_translate("homeWindow", "DASHBOARD"))
        self.content_1_title.setText(_translate("homeWindow", "Cuisine"))
        self.temperature_1.setText(_translate("homeWindow", "Temperature :"))
        self.temperature_1_value.setText(_translate("homeWindow", "29* C"))
        self.light_1.setText(_translate("homeWindow", "Lumière"))
        self.controlTitle.setText(_translate("homeWindow", "CONTROL"))
        self.profileTitle.setText(_translate("homeWindow", "PROFILE"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    homeWindow = QtWidgets.QWidget()
    ui = Ui_homeWindow()
    ui.setupUi(homeWindow)
    homeWindow.show()
    sys.exit(app.exec_())
